// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: demo/v1/demo.proto

// Demo is the example downstream service: it accepts an end-user access token
// over the Freya channel and echoes the verified identity.

package demov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{0}
}

type WhoAmIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Amr           []string               `protobuf:"bytes,5,rep,name=amr,proto3" json:"amr,omitempty"`
	CallerService string                 `protobuf:"bytes,6,opt,name=caller_service,json=callerService,proto3" json:"caller_service,omitempty"` // SPIFFE ID of the service that relayed the call
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_demo_v1_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{1}
}

func (x *WhoAmIResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WhoAmIResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WhoAmIResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WhoAmIResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *WhoAmIResponse) GetAmr() []string {
	if x != nil {
		return x.Amr
	}
	return nil
}

func (x *WhoAmIResponse) GetCallerService() string {
	if x != nil {
		return x.CallerService
	}
	return ""
}

var File_demo_v1_demo_proto protoreflect.FileDescriptor

const file_demo_v1_demo_proto_rawDesc = "" +
	"\n" +
	"\x12demo/v1/demo.proto\x12\ademo.v1\"\x0f\n" +
	"\rWhoAmIRequest\"\xb4\x01\n" +
	"\x0eWhoAmIResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x10\n" +
	"\x03amr\x18\x05 \x03(\tR\x03amr\x12%\n" +
	"\x0ecaller_service\x18\x06 \x01(\tR\rcallerService2A\n" +
	"\x04Demo\x129\n" +
	"\x06WhoAmI\x12\x16.demo.v1.WhoAmIRequest\x1a\x17.demo.v1.WhoAmIResponseBAZ?github.com/go-tangra/go-tangra-auth/v4/api/proto/demo/v1;demov1b\x06proto3"

var (
	file_demo_v1_demo_proto_rawDescOnce sync.Once
	file_demo_v1_demo_proto_rawDescData []byte
)

func file_demo_v1_demo_proto_rawDescGZIP() []byte {
	file_demo_v1_demo_proto_rawDescOnce.Do(func() {
		file_demo_v1_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_v1_demo_proto_rawDesc), len(file_demo_v1_demo_proto_rawDesc)))
	})
	return file_demo_v1_demo_proto_rawDescData
}

var file_demo_v1_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_demo_v1_demo_proto_goTypes = []any{
	(*WhoAmIRequest)(nil),  // 0: demo.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil), // 1: demo.v1.WhoAmIResponse
}
var file_demo_v1_demo_proto_depIdxs = []int32{
	0, // 0: demo.v1.Demo.WhoAmI:input_type -> demo.v1.WhoAmIRequest
	1, // 1: demo.v1.Demo.WhoAmI:output_type -> demo.v1.WhoAmIResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demo_v1_demo_proto_init() }
func file_demo_v1_demo_proto_init() {
	if File_demo_v1_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_v1_demo_proto_rawDesc), len(file_demo_v1_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_v1_demo_proto_goTypes,
		DependencyIndexes: file_demo_v1_demo_proto_depIdxs,
		MessageInfos:      file_demo_v1_demo_proto_msgTypes,
	}.Build()
	File_demo_v1_demo_proto = out.File
	file_demo_v1_demo_proto_goTypes = nil
	file_demo_v1_demo_proto_depIdxs = nil
}
