// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Keys_List_FullMethodName = "/auth.v1.Keys/List"
)

// KeysClient is the client API for Keys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeysClient interface {
	// List returns the currently published verification keys (JWKS equivalent).
	List(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
}

type keysClient struct {
	cc grpc.ClientConnInterface
}

func NewKeysClient(cc grpc.ClientConnInterface) KeysClient {
	return &keysClient{cc}
}

func (c *keysClient) List(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, Keys_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeysServer is the server API for Keys service.
// All implementations must embed UnimplementedKeysServer
// for forward compatibility.
type KeysServer interface {
	// List returns the currently published verification keys (JWKS equivalent).
	List(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	mustEmbedUnimplementedKeysServer()
}

// UnimplementedKeysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeysServer struct{}

func (UnimplementedKeysServer) List(context.Context, *ListKeysRequest) (*ListKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedKeysServer) mustEmbedUnimplementedKeysServer() {}
func (UnimplementedKeysServer) testEmbeddedByValue()              {}

// UnsafeKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeysServer will
// result in compilation errors.
type UnsafeKeysServer interface {
	mustEmbedUnimplementedKeysServer()
}

func RegisterKeysServer(s grpc.ServiceRegistrar, srv KeysServer) {
	// If the following call panics, it indicates UnimplementedKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Keys_ServiceDesc, srv)
}

func _Keys_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeysServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keys_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeysServer).List(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Keys_ServiceDesc is the grpc.ServiceDesc for Keys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Keys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.Keys",
	HandlerType: (*KeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Keys_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}

const (
	Sessions_RevokedSince_FullMethodName = "/auth.v1.Sessions/RevokedSince"
	Sessions_Watch_FullMethodName        = "/auth.v1.Sessions/Watch"
	Sessions_Introspect_FullMethodName   = "/auth.v1.Sessions/Introspect"
	Sessions_Exchange_FullMethodName     = "/auth.v1.Sessions/Exchange"
	Sessions_MintToken_FullMethodName    = "/auth.v1.Sessions/MintToken"
)

// SessionsClient is the client API for Sessions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionsClient interface {
	// RevokedSince returns revocation entries after the cursor (bounded delay
	// feed for offline verifiers). Cursor "" = last 60 minutes.
	RevokedSince(ctx context.Context, in *RevokedSinceRequest, opts ...grpc.CallOption) (*RevokedSinceResponse, error)
	// Watch streams revocation entries as they happen (optional fast path).
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Revocation], error)
	// Introspect validates a token server-side (rare path; audited).
	Introspect(ctx context.Context, in *IntrospectRequest, opts ...grpc.CallOption) (*IntrospectResponse, error)
	// Exchange resolves a browser session cookie exactly like the console path
	// and mints a platform access token for it. Policy: the gateway identity only.
	Exchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error)
	// MintToken refreshes a token for a session that is already verified
	// (before expiry, without re-sending the cookie). Refused once the session
	// is no longer live. Policy: the gateway identity only.
	MintToken(ctx context.Context, in *MintTokenRequest, opts ...grpc.CallOption) (*MintTokenResponse, error)
}

type sessionsClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionsClient(cc grpc.ClientConnInterface) SessionsClient {
	return &sessionsClient{cc}
}

func (c *sessionsClient) RevokedSince(ctx context.Context, in *RevokedSinceRequest, opts ...grpc.CallOption) (*RevokedSinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokedSinceResponse)
	err := c.cc.Invoke(ctx, Sessions_RevokedSince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Revocation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sessions_ServiceDesc.Streams[0], Sessions_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, Revocation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sessions_WatchClient = grpc.ServerStreamingClient[Revocation]

func (c *sessionsClient) Introspect(ctx context.Context, in *IntrospectRequest, opts ...grpc.CallOption) (*IntrospectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntrospectResponse)
	err := c.cc.Invoke(ctx, Sessions_Introspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Exchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeResponse)
	err := c.cc.Invoke(ctx, Sessions_Exchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) MintToken(ctx context.Context, in *MintTokenRequest, opts ...grpc.CallOption) (*MintTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintTokenResponse)
	err := c.cc.Invoke(ctx, Sessions_MintToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionsServer is the server API for Sessions service.
// All implementations must embed UnimplementedSessionsServer
// for forward compatibility.
type SessionsServer interface {
	// RevokedSince returns revocation entries after the cursor (bounded delay
	// feed for offline verifiers). Cursor "" = last 60 minutes.
	RevokedSince(context.Context, *RevokedSinceRequest) (*RevokedSinceResponse, error)
	// Watch streams revocation entries as they happen (optional fast path).
	Watch(*WatchRequest, grpc.ServerStreamingServer[Revocation]) error
	// Introspect validates a token server-side (rare path; audited).
	Introspect(context.Context, *IntrospectRequest) (*IntrospectResponse, error)
	// Exchange resolves a browser session cookie exactly like the console path
	// and mints a platform access token for it. Policy: the gateway identity only.
	Exchange(context.Context, *ExchangeRequest) (*ExchangeResponse, error)
	// MintToken refreshes a token for a session that is already verified
	// (before expiry, without re-sending the cookie). Refused once the session
	// is no longer live. Policy: the gateway identity only.
	MintToken(context.Context, *MintTokenRequest) (*MintTokenResponse, error)
	mustEmbedUnimplementedSessionsServer()
}

// UnimplementedSessionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionsServer struct{}

func (UnimplementedSessionsServer) RevokedSince(context.Context, *RevokedSinceRequest) (*RevokedSinceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokedSince not implemented")
}
func (UnimplementedSessionsServer) Watch(*WatchRequest, grpc.ServerStreamingServer[Revocation]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSessionsServer) Introspect(context.Context, *IntrospectRequest) (*IntrospectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Introspect not implemented")
}
func (UnimplementedSessionsServer) Exchange(context.Context, *ExchangeRequest) (*ExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exchange not implemented")
}
func (UnimplementedSessionsServer) MintToken(context.Context, *MintTokenRequest) (*MintTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintToken not implemented")
}
func (UnimplementedSessionsServer) mustEmbedUnimplementedSessionsServer() {}
func (UnimplementedSessionsServer) testEmbeddedByValue()                  {}

// UnsafeSessionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionsServer will
// result in compilation errors.
type UnsafeSessionsServer interface {
	mustEmbedUnimplementedSessionsServer()
}

func RegisterSessionsServer(s grpc.ServiceRegistrar, srv SessionsServer) {
	// If the following call panics, it indicates UnimplementedSessionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sessions_ServiceDesc, srv)
}

func _Sessions_RevokedSince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokedSinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).RevokedSince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_RevokedSince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).RevokedSince(ctx, req.(*RevokedSinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionsServer).Watch(m, &grpc.GenericServerStream[WatchRequest, Revocation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sessions_WatchServer = grpc.ServerStreamingServer[Revocation]

func _Sessions_Introspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntrospectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Introspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Introspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Introspect(ctx, req.(*IntrospectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Exchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Exchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Exchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Exchange(ctx, req.(*ExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_MintToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).MintToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_MintToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).MintToken(ctx, req.(*MintTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sessions_ServiceDesc is the grpc.ServiceDesc for Sessions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sessions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.Sessions",
	HandlerType: (*SessionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RevokedSince",
			Handler:    _Sessions_RevokedSince_Handler,
		},
		{
			MethodName: "Introspect",
			Handler:    _Sessions_Introspect_Handler,
		},
		{
			MethodName: "Exchange",
			Handler:    _Sessions_Exchange_Handler,
		},
		{
			MethodName: "MintToken",
			Handler:    _Sessions_MintToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Sessions_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "auth/v1/auth.proto",
}

const (
	Enrollment_MintEnrollmentToken_FullMethodName   = "/auth.v1.Enrollment/MintEnrollmentToken"
	Enrollment_VerifyEnrollmentToken_FullMethodName = "/auth.v1.Enrollment/VerifyEnrollmentToken"
)

// EnrollmentClient is the client API for Enrollment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnrollmentClient interface {
	// MintEnrollmentToken issues a single-use, short-lived token authorising the
	// enrollment of the given SPIFFE paths in a tenant (the credential a workload
	// presents to lcm for its FIRST SVID). Policy: gateway/console identities only.
	MintEnrollmentToken(ctx context.Context, in *MintEnrollmentTokenRequest, opts ...grpc.CallOption) (*MintEnrollmentTokenResponse, error)
	// VerifyEnrollmentToken validates a token (signature, audience, expiry) and
	// BURNS its jti so it can be used at most once. Policy: the lcm identity only.
	VerifyEnrollmentToken(ctx context.Context, in *VerifyEnrollmentTokenRequest, opts ...grpc.CallOption) (*VerifyEnrollmentTokenResponse, error)
}

type enrollmentClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentClient(cc grpc.ClientConnInterface) EnrollmentClient {
	return &enrollmentClient{cc}
}

func (c *enrollmentClient) MintEnrollmentToken(ctx context.Context, in *MintEnrollmentTokenRequest, opts ...grpc.CallOption) (*MintEnrollmentTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintEnrollmentTokenResponse)
	err := c.cc.Invoke(ctx, Enrollment_MintEnrollmentToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentClient) VerifyEnrollmentToken(ctx context.Context, in *VerifyEnrollmentTokenRequest, opts ...grpc.CallOption) (*VerifyEnrollmentTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyEnrollmentTokenResponse)
	err := c.cc.Invoke(ctx, Enrollment_VerifyEnrollmentToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentServer is the server API for Enrollment service.
// All implementations must embed UnimplementedEnrollmentServer
// for forward compatibility.
type EnrollmentServer interface {
	// MintEnrollmentToken issues a single-use, short-lived token authorising the
	// enrollment of the given SPIFFE paths in a tenant (the credential a workload
	// presents to lcm for its FIRST SVID). Policy: gateway/console identities only.
	MintEnrollmentToken(context.Context, *MintEnrollmentTokenRequest) (*MintEnrollmentTokenResponse, error)
	// VerifyEnrollmentToken validates a token (signature, audience, expiry) and
	// BURNS its jti so it can be used at most once. Policy: the lcm identity only.
	VerifyEnrollmentToken(context.Context, *VerifyEnrollmentTokenRequest) (*VerifyEnrollmentTokenResponse, error)
	mustEmbedUnimplementedEnrollmentServer()
}

// UnimplementedEnrollmentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrollmentServer struct{}

func (UnimplementedEnrollmentServer) MintEnrollmentToken(context.Context, *MintEnrollmentTokenRequest) (*MintEnrollmentTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintEnrollmentToken not implemented")
}
func (UnimplementedEnrollmentServer) VerifyEnrollmentToken(context.Context, *VerifyEnrollmentTokenRequest) (*VerifyEnrollmentTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyEnrollmentToken not implemented")
}
func (UnimplementedEnrollmentServer) mustEmbedUnimplementedEnrollmentServer() {}
func (UnimplementedEnrollmentServer) testEmbeddedByValue()                    {}

// UnsafeEnrollmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentServer will
// result in compilation errors.
type UnsafeEnrollmentServer interface {
	mustEmbedUnimplementedEnrollmentServer()
}

func RegisterEnrollmentServer(s grpc.ServiceRegistrar, srv EnrollmentServer) {
	// If the following call panics, it indicates UnimplementedEnrollmentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Enrollment_ServiceDesc, srv)
}

func _Enrollment_MintEnrollmentToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintEnrollmentTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServer).MintEnrollmentToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enrollment_MintEnrollmentToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServer).MintEnrollmentToken(ctx, req.(*MintEnrollmentTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enrollment_VerifyEnrollmentToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEnrollmentTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServer).VerifyEnrollmentToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enrollment_VerifyEnrollmentToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServer).VerifyEnrollmentToken(ctx, req.(*VerifyEnrollmentTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Enrollment_ServiceDesc is the grpc.ServiceDesc for Enrollment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Enrollment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.Enrollment",
	HandlerType: (*EnrollmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintEnrollmentToken",
			Handler:    _Enrollment_MintEnrollmentToken_Handler,
		},
		{
			MethodName: "VerifyEnrollmentToken",
			Handler:    _Enrollment_VerifyEnrollmentToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}

const (
	Authorization_Check_FullMethodName               = "/auth.v1.Authorization/Check"
	Authorization_BatchCheck_FullMethodName          = "/auth.v1.Authorization/BatchCheck"
	Authorization_RegisterPermissions_FullMethodName = "/auth.v1.Authorization/RegisterPermissions"
)

// AuthorizationClient is the client API for Authorization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorizationClient interface {
	// Check answers "may user perform action on resource in tenant".
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// BatchCheck answers many questions for the same user/tenant.
	BatchCheck(ctx context.Context, in *BatchCheckRequest, opts ...grpc.CallOption) (*BatchCheckResponse, error)
	// RegisterPermissions declares the resources/actions a service exposes
	// (FR-015). Idempotent; the caller's SPIFFE ID is recorded as registrant.
	RegisterPermissions(ctx context.Context, in *RegisterPermissionsRequest, opts ...grpc.CallOption) (*RegisterPermissionsResponse, error)
}

type authorizationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationClient(cc grpc.ClientConnInterface) AuthorizationClient {
	return &authorizationClient{cc}
}

func (c *authorizationClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, Authorization_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) BatchCheck(ctx context.Context, in *BatchCheckRequest, opts ...grpc.CallOption) (*BatchCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCheckResponse)
	err := c.cc.Invoke(ctx, Authorization_BatchCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationClient) RegisterPermissions(ctx context.Context, in *RegisterPermissionsRequest, opts ...grpc.CallOption) (*RegisterPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterPermissionsResponse)
	err := c.cc.Invoke(ctx, Authorization_RegisterPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServer is the server API for Authorization service.
// All implementations must embed UnimplementedAuthorizationServer
// for forward compatibility.
type AuthorizationServer interface {
	// Check answers "may user perform action on resource in tenant".
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	// BatchCheck answers many questions for the same user/tenant.
	BatchCheck(context.Context, *BatchCheckRequest) (*BatchCheckResponse, error)
	// RegisterPermissions declares the resources/actions a service exposes
	// (FR-015). Idempotent; the caller's SPIFFE ID is recorded as registrant.
	RegisterPermissions(context.Context, *RegisterPermissionsRequest) (*RegisterPermissionsResponse, error)
	mustEmbedUnimplementedAuthorizationServer()
}

// UnimplementedAuthorizationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthorizationServer struct{}

func (UnimplementedAuthorizationServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedAuthorizationServer) BatchCheck(context.Context, *BatchCheckRequest) (*BatchCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCheck not implemented")
}
func (UnimplementedAuthorizationServer) RegisterPermissions(context.Context, *RegisterPermissionsRequest) (*RegisterPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterPermissions not implemented")
}
func (UnimplementedAuthorizationServer) mustEmbedUnimplementedAuthorizationServer() {}
func (UnimplementedAuthorizationServer) testEmbeddedByValue()                       {}

// UnsafeAuthorizationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationServer will
// result in compilation errors.
type UnsafeAuthorizationServer interface {
	mustEmbedUnimplementedAuthorizationServer()
}

func RegisterAuthorizationServer(s grpc.ServiceRegistrar, srv AuthorizationServer) {
	// If the following call panics, it indicates UnimplementedAuthorizationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Authorization_ServiceDesc, srv)
}

func _Authorization_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authorization_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_BatchCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).BatchCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authorization_BatchCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).BatchCheck(ctx, req.(*BatchCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorization_RegisterPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).RegisterPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authorization_RegisterPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).RegisterPermissions(ctx, req.(*RegisterPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authorization_ServiceDesc is the grpc.ServiceDesc for Authorization service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authorization_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.Authorization",
	HandlerType: (*AuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Authorization_Check_Handler,
		},
		{
			MethodName: "BatchCheck",
			Handler:    _Authorization_BatchCheck_Handler,
		},
		{
			MethodName: "RegisterPermissions",
			Handler:    _Authorization_RegisterPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}

const (
	Profiles_Lookup_FullMethodName      = "/auth.v1.Profiles/Lookup"
	Profiles_ListMembers_FullMethodName = "/auth.v1.Profiles/ListMembers"
)

// ProfilesClient is the client API for Profiles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Profiles answers "who is this user id" for services on the Freya channel.
// The tenant must match the caller's grant like Authorization.Check; the phone
// number is never returned.
type ProfilesClient interface {
	Lookup(ctx context.Context, in *LookupProfilesRequest, opts ...grpc.CallOption) (*LookupProfilesResponse, error)
	// ListMembers pages the ids of the active members of a tenant (feature 006:
	// "everyone" messages); with user_ids it returns the active ones among
	// them. Policy: services allowed by policy.yaml (the notification module).
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
}

type profilesClient struct {
	cc grpc.ClientConnInterface
}

func NewProfilesClient(cc grpc.ClientConnInterface) ProfilesClient {
	return &profilesClient{cc}
}

func (c *profilesClient) Lookup(ctx context.Context, in *LookupProfilesRequest, opts ...grpc.CallOption) (*LookupProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupProfilesResponse)
	err := c.cc.Invoke(ctx, Profiles_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, Profiles_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfilesServer is the server API for Profiles service.
// All implementations must embed UnimplementedProfilesServer
// for forward compatibility.
//
// Profiles answers "who is this user id" for services on the Freya channel.
// The tenant must match the caller's grant like Authorization.Check; the phone
// number is never returned.
type ProfilesServer interface {
	Lookup(context.Context, *LookupProfilesRequest) (*LookupProfilesResponse, error)
	// ListMembers pages the ids of the active members of a tenant (feature 006:
	// "everyone" messages); with user_ids it returns the active ones among
	// them. Policy: services allowed by policy.yaml (the notification module).
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	mustEmbedUnimplementedProfilesServer()
}

// UnimplementedProfilesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfilesServer struct{}

func (UnimplementedProfilesServer) Lookup(context.Context, *LookupProfilesRequest) (*LookupProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedProfilesServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedProfilesServer) mustEmbedUnimplementedProfilesServer() {}
func (UnimplementedProfilesServer) testEmbeddedByValue()                  {}

// UnsafeProfilesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfilesServer will
// result in compilation errors.
type UnsafeProfilesServer interface {
	mustEmbedUnimplementedProfilesServer()
}

func RegisterProfilesServer(s grpc.ServiceRegistrar, srv ProfilesServer) {
	// If the following call panics, it indicates UnimplementedProfilesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Profiles_ServiceDesc, srv)
}

func _Profiles_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profiles_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).Lookup(ctx, req.(*LookupProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Profiles_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Profiles_ServiceDesc is the grpc.ServiceDesc for Profiles service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Profiles_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.Profiles",
	HandlerType: (*ProfilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _Profiles_Lookup_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _Profiles_ListMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}
