// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysRequest) Reset() {
	*x = ListKeysRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysRequest) ProtoMessage() {}

func (x *ListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysRequest.ProtoReflect.Descriptor instead.
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

type ListKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*Key                 `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ListKeysResponse) GetKeys() []*Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kid           string                 `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	Kty           string                 `protobuf:"bytes,2,opt,name=kty,proto3" json:"kty,omitempty"`                              // "OKP"
	Crv           string                 `protobuf:"bytes,3,opt,name=crv,proto3" json:"crv,omitempty"`                              // "Ed25519"
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // raw 32 bytes
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`                          // active | retiring | retired
	NotAfter      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`    // last moment a token signed with it can be valid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *Key) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *Key) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *Key) GetCrv() string {
	if x != nil {
		return x.Crv
	}
	return ""
}

func (x *Key) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Key) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Key) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

type RevokedSinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokedSinceRequest) Reset() {
	*x = RevokedSinceRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokedSinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokedSinceRequest) ProtoMessage() {}

func (x *RevokedSinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokedSinceRequest.ProtoReflect.Descriptor instead.
func (*RevokedSinceRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RevokedSinceRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *RevokedSinceRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RevokedSinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revocations   []*Revocation          `protobuf:"bytes,1,rep,name=revocations,proto3" json:"revocations,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokedSinceResponse) Reset() {
	*x = RevokedSinceResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokedSinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokedSinceResponse) ProtoMessage() {}

func (x *RevokedSinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokedSinceResponse.ProtoReflect.Descriptor instead.
func (*RevokedSinceResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RevokedSinceResponse) GetRevocations() []*Revocation {
	if x != nil {
		return x.Revocations
	}
	return nil
}

func (x *RevokedSinceResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *WatchRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type Revocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // session | user | tenant
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"` // closed vocabulary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revocation) Reset() {
	*x = Revocation{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revocation) ProtoMessage() {}

func (x *Revocation) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revocation.ProtoReflect.Descriptor instead.
func (*Revocation) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *Revocation) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Revocation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Revocation) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Revocation) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Revocation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type IntrospectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectRequest) Reset() {
	*x = IntrospectRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectRequest) ProtoMessage() {}

func (x *IntrospectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectRequest.ProtoReflect.Descriptor instead.
func (*IntrospectRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *IntrospectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type IntrospectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // expired | revoked | invalid | tenant_suspended | user_inactive
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Roles         []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectResponse) Reset() {
	*x = IntrospectResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectResponse) ProtoMessage() {}

func (x *IntrospectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectResponse.ProtoReflect.Descriptor instead.
func (*IntrospectResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *IntrospectResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *IntrospectResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *IntrospectResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IntrospectResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IntrospectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IntrospectResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *IntrospectResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CookieSecret  string                 `protobuf:"bytes,1,opt,name=cookie_secret,json=cookieSecret,proto3" json:"cookie_secret,omitempty"`
	Audience      string                 `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"` // optional aud claim (e.g. "gateway")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ExchangeRequest) GetCookieSecret() string {
	if x != nil {
		return x.CookieSecret
	}
	return ""
}

func (x *ExchangeRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

type SessionIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Amr           []string               `protobuf:"bytes,5,rep,name=amr,proto3" json:"amr,omitempty"`
	Operator      bool                   `protobuf:"varint,6,opt,name=operator,proto3" json:"operator,omitempty"`                         // member of the platform tenant
	DisplayName   string                 `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // "First Last" | explicit display name | email local part
	AvatarUrl     string                 `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`       // gateway-relative, content-addressed; "" when none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionIdentity) Reset() {
	*x = SessionIdentity{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionIdentity) ProtoMessage() {}

func (x *SessionIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionIdentity.ProtoReflect.Descriptor instead.
func (*SessionIdentity) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *SessionIdentity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionIdentity) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SessionIdentity) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionIdentity) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *SessionIdentity) GetAmr() []string {
	if x != nil {
		return x.Amr
	}
	return nil
}

func (x *SessionIdentity) GetOperator() bool {
	if x != nil {
		return x.Operator
	}
	return false
}

func (x *SessionIdentity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SessionIdentity) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type ExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *SessionIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeResponse) Reset() {
	*x = ExchangeResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResponse) ProtoMessage() {}

func (x *ExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ExchangeResponse) GetIdentity() *SessionIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ExchangeResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ExchangeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type MintTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Audience      string                 `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintTokenRequest) Reset() {
	*x = MintTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintTokenRequest) ProtoMessage() {}

func (x *MintTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintTokenRequest.ProtoReflect.Descriptor instead.
func (*MintTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *MintTokenRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MintTokenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MintTokenRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

type MintTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *SessionIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintTokenResponse) Reset() {
	*x = MintTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintTokenResponse) ProtoMessage() {}

func (x *MintTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintTokenResponse.ProtoReflect.Descriptor instead.
func (*MintTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *MintTokenResponse) GetIdentity() *SessionIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *MintTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *MintTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type MintEnrollmentTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SpiffePaths   []string               `protobuf:"bytes,2,rep,name=spiffe_paths,json=spiffePaths,proto3" json:"spiffe_paths,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintEnrollmentTokenRequest) Reset() {
	*x = MintEnrollmentTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintEnrollmentTokenRequest) ProtoMessage() {}

func (x *MintEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*MintEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *MintEnrollmentTokenRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MintEnrollmentTokenRequest) GetSpiffePaths() []string {
	if x != nil {
		return x.SpiffePaths
	}
	return nil
}

func (x *MintEnrollmentTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type MintEnrollmentTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintEnrollmentTokenResponse) Reset() {
	*x = MintEnrollmentTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintEnrollmentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintEnrollmentTokenResponse) ProtoMessage() {}

func (x *MintEnrollmentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintEnrollmentTokenResponse.ProtoReflect.Descriptor instead.
func (*MintEnrollmentTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *MintEnrollmentTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MintEnrollmentTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type VerifyEnrollmentTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEnrollmentTokenRequest) Reset() {
	*x = VerifyEnrollmentTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEnrollmentTokenRequest) ProtoMessage() {}

func (x *VerifyEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyEnrollmentTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyEnrollmentTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SpiffePaths   []string               `protobuf:"bytes,2,rep,name=spiffe_paths,json=spiffePaths,proto3" json:"spiffe_paths,omitempty"`
	Jti           string                 `protobuf:"bytes,3,opt,name=jti,proto3" json:"jti,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEnrollmentTokenResponse) Reset() {
	*x = VerifyEnrollmentTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEnrollmentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEnrollmentTokenResponse) ProtoMessage() {}

func (x *VerifyEnrollmentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEnrollmentTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyEnrollmentTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *VerifyEnrollmentTokenResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *VerifyEnrollmentTokenResponse) GetSpiffePaths() []string {
	if x != nil {
		return x.SpiffePaths
	}
	return nil
}

func (x *VerifyEnrollmentTokenResponse) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`                                                                         // e.g. "invoices"
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                                                                             // e.g. "read"
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // reserved for conditions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *CheckRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                    // role:<slug> | no_permission | user_inactive | tenant_suspended | unknown_permission
	PolicyVersion string                 `protobuf:"bytes,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"` // tenant version used for the decision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckResponse) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

type BatchCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permissions   []*PermissionRef       `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckRequest) Reset() {
	*x = BatchCheckRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckRequest) ProtoMessage() {}

func (x *BatchCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{20}
}

func (x *BatchCheckRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BatchCheckRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BatchCheckRequest) GetPermissions() []*PermissionRef {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type PermissionRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionRef) Reset() {
	*x = PermissionRef{}
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRef) ProtoMessage() {}

func (x *PermissionRef) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRef.ProtoReflect.Descriptor instead.
func (*PermissionRef) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *PermissionRef) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionRef) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type BatchCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CheckResponse       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckResponse) Reset() {
	*x = BatchCheckResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckResponse) ProtoMessage() {}

func (x *BatchCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckResponse.ProtoReflect.Descriptor instead.
func (*BatchCheckResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{22}
}

func (x *BatchCheckResponse) GetResults() []*CheckResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type RegisterPermissionsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Permissions []*PermissionDef       `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// tenant_ids empty = register for every tenant the service is entitled to serve.
	TenantIds []string `protobuf:"bytes,2,rep,name=tenant_ids,json=tenantIds,proto3" json:"tenant_ids,omitempty"`
	// builtin_grants adds the registrant's own permissions to built-in roles
	// (owner, admin, member, auditor, operator) of every tenant; idempotent.
	// Permissions not in this request are refused (feature 005).
	BuiltinGrants []*BuiltinGrant `protobuf:"bytes,3,rep,name=builtin_grants,json=builtinGrants,proto3" json:"builtin_grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPermissionsRequest) Reset() {
	*x = RegisterPermissionsRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPermissionsRequest) ProtoMessage() {}

func (x *RegisterPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPermissionsRequest.ProtoReflect.Descriptor instead.
func (*RegisterPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{23}
}

func (x *RegisterPermissionsRequest) GetPermissions() []*PermissionDef {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RegisterPermissionsRequest) GetTenantIds() []string {
	if x != nil {
		return x.TenantIds
	}
	return nil
}

func (x *RegisterPermissionsRequest) GetBuiltinGrants() []*BuiltinGrant {
	if x != nil {
		return x.BuiltinGrants
	}
	return nil
}

type BuiltinGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuiltinGrant) Reset() {
	*x = BuiltinGrant{}
	mi := &file_auth_v1_auth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuiltinGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuiltinGrant) ProtoMessage() {}

func (x *BuiltinGrant) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuiltinGrant.ProtoReflect.Descriptor instead.
func (*BuiltinGrant) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{24}
}

func (x *BuiltinGrant) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BuiltinGrant) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type PermissionDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionDef) Reset() {
	*x = PermissionDef{}
	mi := &file_auth_v1_auth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionDef) ProtoMessage() {}

func (x *PermissionDef) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionDef.ProtoReflect.Descriptor instead.
func (*PermissionDef) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{25}
}

func (x *PermissionDef) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionDef) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RegisterPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    uint32                 `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPermissionsResponse) Reset() {
	*x = RegisterPermissionsResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPermissionsResponse) ProtoMessage() {}

func (x *RegisterPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPermissionsResponse.ProtoReflect.Descriptor instead.
func (*RegisterPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{26}
}

func (x *RegisterPermissionsResponse) GetRegistered() uint32 {
	if x != nil {
		return x.Registered
	}
	return 0
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`                  // last id of the previous page
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                   // 1..1000, default 1000
	UserIds       []string               `protobuf:"bytes,4,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // at most 1000: filter instead of paging
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{27}
}

func (x *ListMembersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListMembersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListMembersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMembersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`          // active users only, ordered by id
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // empty on the last page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{28}
}

func (x *ListMembersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *ListMembersResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type LookupProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // at most 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupProfilesRequest) Reset() {
	*x = LookupProfilesRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProfilesRequest) ProtoMessage() {}

func (x *LookupProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProfilesRequest.ProtoReflect.Descriptor instead.
func (*LookupProfilesRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{29}
}

func (x *LookupProfilesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LookupProfilesRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type PublicProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicProfile) Reset() {
	*x = PublicProfile{}
	mi := &file_auth_v1_auth_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicProfile) ProtoMessage() {}

func (x *PublicProfile) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicProfile.ProtoReflect.Descriptor instead.
func (*PublicProfile) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{30}
}

func (x *PublicProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PublicProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PublicProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type LookupProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*PublicProfile       `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"` // unknown ids omitted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupProfilesResponse) Reset() {
	*x = LookupProfilesResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProfilesResponse) ProtoMessage() {}

func (x *LookupProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProfilesResponse.ProtoReflect.Descriptor instead.
func (*LookupProfilesResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{31}
}

func (x *LookupProfilesResponse) GetProfiles() []*PublicProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x11\n" +
	"\x0fListKeysRequest\"4\n" +
	"\x10ListKeysResponse\x12 \n" +
	"\x04keys\x18\x01 \x03(\v2\f.auth.v1.KeyR\x04keys\"\xa9\x01\n" +
	"\x03Key\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\x12\x10\n" +
	"\x03kty\x18\x02 \x01(\tR\x03kty\x12\x10\n" +
	"\x03crv\x18\x03 \x01(\tR\x03crv\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x127\n" +
	"\tnot_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\"C\n" +
	"\x13RevokedSinceRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"n\n" +
	"\x14RevokedSinceResponse\x125\n" +
	"\vrevocations\x18\x01 \x03(\v2\x13.auth.v1.RevocationR\vrevocations\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"&\n" +
	"\fWatchRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\"\xa0\x01\n" +
	"\n" +
	"Revocation\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\")\n" +
	"\x11IntrospectRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xea\x01\n" +
	"\x12IntrospectResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"R\n" +
	"\x0fExchangeRequest\x12#\n" +
	"\rcookie_secret\x18\x01 \x01(\tR\fcookieSecret\x12\x1a\n" +
	"\baudience\x18\x02 \x01(\tR\baudience\"\xec\x01\n" +
	"\x0fSessionIdentity\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x10\n" +
	"\x03amr\x18\x05 \x03(\tR\x03amr\x12\x1a\n" +
	"\boperator\x18\x06 \x01(\bR\boperator\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\b \x01(\tR\tavatarUrl\"\xa6\x01\n" +
	"\x10ExchangeResponse\x124\n" +
	"\bidentity\x18\x01 \x01(\v2\x18.auth.v1.SessionIdentityR\bidentity\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"j\n" +
	"\x10MintTokenRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\baudience\x18\x03 \x01(\tR\baudience\"\xa7\x01\n" +
	"\x11MintTokenResponse\x124\n" +
	"\bidentity\x18\x01 \x01(\v2\x18.auth.v1.SessionIdentityR\bidentity\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"}\n" +
	"\x1aMintEnrollmentTokenRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fspiffe_paths\x18\x02 \x03(\tR\vspiffePaths\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"n\n" +
	"\x1bMintEnrollmentTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"4\n" +
	"\x1cVerifyEnrollmentTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"q\n" +
	"\x1dVerifyEnrollmentTokenResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fspiffe_paths\x18\x02 \x03(\tR\vspiffePaths\x12\x10\n" +
	"\x03jti\x18\x03 \x01(\tR\x03jti\"\xf2\x01\n" +
	"\fCheckRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12<\n" +
	"\acontext\x18\x05 \x03(\v2\".auth.v1.CheckRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\tR\rpolicyVersion\"\x83\x01\n" +
	"\x11BatchCheckRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x128\n" +
	"\vpermissions\x18\x03 \x03(\v2\x16.auth.v1.PermissionRefR\vpermissions\"C\n" +
	"\rPermissionRef\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"F\n" +
	"\x12BatchCheckResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.auth.v1.CheckResponseR\aresults\"\xb3\x01\n" +
	"\x1aRegisterPermissionsRequest\x128\n" +
	"\vpermissions\x18\x01 \x03(\v2\x16.auth.v1.PermissionDefR\vpermissions\x12\x1d\n" +
	"\n" +
	"tenant_ids\x18\x02 \x03(\tR\ttenantIds\x12<\n" +
	"\x0ebuiltin_grants\x18\x03 \x03(\v2\x15.auth.v1.BuiltinGrantR\rbuiltinGrants\"D\n" +
	"\fBuiltinGrant\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"e\n" +
	"\rPermissionDef\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"=\n" +
	"\x1bRegisterPermissionsResponse\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x01(\rR\n" +
	"registered\"z\n" +
	"\x12ListMembersRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x19\n" +
	"\buser_ids\x18\x04 \x03(\tR\auserIds\"Q\n" +
	"\x13ListMembersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"O\n" +
	"\x15LookupProfilesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"j\n" +
	"\rPublicProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"L\n" +
	"\x16LookupProfilesResponse\x122\n" +
	"\bprofiles\x18\x01 \x03(\v2\x16.auth.v1.PublicProfileR\bprofiles2C\n" +
	"\x04Keys\x12;\n" +
	"\x04List\x12\x18.auth.v1.ListKeysRequest\x1a\x19.auth.v1.ListKeysResponse2\xda\x02\n" +
	"\bSessions\x12K\n" +
	"\fRevokedSince\x12\x1c.auth.v1.RevokedSinceRequest\x1a\x1d.auth.v1.RevokedSinceResponse\x125\n" +
	"\x05Watch\x12\x15.auth.v1.WatchRequest\x1a\x13.auth.v1.Revocation0\x01\x12E\n" +
	"\n" +
	"Introspect\x12\x1a.auth.v1.IntrospectRequest\x1a\x1b.auth.v1.IntrospectResponse\x12?\n" +
	"\bExchange\x12\x18.auth.v1.ExchangeRequest\x1a\x19.auth.v1.ExchangeResponse\x12B\n" +
	"\tMintToken\x12\x19.auth.v1.MintTokenRequest\x1a\x1a.auth.v1.MintTokenResponse2\xd6\x01\n" +
	"\n" +
	"Enrollment\x12`\n" +
	"\x13MintEnrollmentToken\x12#.auth.v1.MintEnrollmentTokenRequest\x1a$.auth.v1.MintEnrollmentTokenResponse\x12f\n" +
	"\x15VerifyEnrollmentToken\x12%.auth.v1.VerifyEnrollmentTokenRequest\x1a&.auth.v1.VerifyEnrollmentTokenResponse2\xf0\x01\n" +
	"\rAuthorization\x126\n" +
	"\x05Check\x12\x15.auth.v1.CheckRequest\x1a\x16.auth.v1.CheckResponse\x12E\n" +
	"\n" +
	"BatchCheck\x12\x1a.auth.v1.BatchCheckRequest\x1a\x1b.auth.v1.BatchCheckResponse\x12`\n" +
	"\x13RegisterPermissions\x12#.auth.v1.RegisterPermissionsRequest\x1a$.auth.v1.RegisterPermissionsResponse2\x9f\x01\n" +
	"\bProfiles\x12I\n" +
	"\x06Lookup\x12\x1e.auth.v1.LookupProfilesRequest\x1a\x1f.auth.v1.LookupProfilesResponse\x12H\n" +
	"\vListMembers\x12\x1b.auth.v1.ListMembersRequest\x1a\x1c.auth.v1.ListMembersResponseBBZ@github.com/go-freya/freya/services/auth/api/proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_auth_v1_auth_proto_goTypes = []any{
	(*ListKeysRequest)(nil),               // 0: auth.v1.ListKeysRequest
	(*ListKeysResponse)(nil),              // 1: auth.v1.ListKeysResponse
	(*Key)(nil),                           // 2: auth.v1.Key
	(*RevokedSinceRequest)(nil),           // 3: auth.v1.RevokedSinceRequest
	(*RevokedSinceResponse)(nil),          // 4: auth.v1.RevokedSinceResponse
	(*WatchRequest)(nil),                  // 5: auth.v1.WatchRequest
	(*Revocation)(nil),                    // 6: auth.v1.Revocation
	(*IntrospectRequest)(nil),             // 7: auth.v1.IntrospectRequest
	(*IntrospectResponse)(nil),            // 8: auth.v1.IntrospectResponse
	(*ExchangeRequest)(nil),               // 9: auth.v1.ExchangeRequest
	(*SessionIdentity)(nil),               // 10: auth.v1.SessionIdentity
	(*ExchangeResponse)(nil),              // 11: auth.v1.ExchangeResponse
	(*MintTokenRequest)(nil),              // 12: auth.v1.MintTokenRequest
	(*MintTokenResponse)(nil),             // 13: auth.v1.MintTokenResponse
	(*MintEnrollmentTokenRequest)(nil),    // 14: auth.v1.MintEnrollmentTokenRequest
	(*MintEnrollmentTokenResponse)(nil),   // 15: auth.v1.MintEnrollmentTokenResponse
	(*VerifyEnrollmentTokenRequest)(nil),  // 16: auth.v1.VerifyEnrollmentTokenRequest
	(*VerifyEnrollmentTokenResponse)(nil), // 17: auth.v1.VerifyEnrollmentTokenResponse
	(*CheckRequest)(nil),                  // 18: auth.v1.CheckRequest
	(*CheckResponse)(nil),                 // 19: auth.v1.CheckResponse
	(*BatchCheckRequest)(nil),             // 20: auth.v1.BatchCheckRequest
	(*PermissionRef)(nil),                 // 21: auth.v1.PermissionRef
	(*BatchCheckResponse)(nil),            // 22: auth.v1.BatchCheckResponse
	(*RegisterPermissionsRequest)(nil),    // 23: auth.v1.RegisterPermissionsRequest
	(*BuiltinGrant)(nil),                  // 24: auth.v1.BuiltinGrant
	(*PermissionDef)(nil),                 // 25: auth.v1.PermissionDef
	(*RegisterPermissionsResponse)(nil),   // 26: auth.v1.RegisterPermissionsResponse
	(*ListMembersRequest)(nil),            // 27: auth.v1.ListMembersRequest
	(*ListMembersResponse)(nil),           // 28: auth.v1.ListMembersResponse
	(*LookupProfilesRequest)(nil),         // 29: auth.v1.LookupProfilesRequest
	(*PublicProfile)(nil),                 // 30: auth.v1.PublicProfile
	(*LookupProfilesResponse)(nil),        // 31: auth.v1.LookupProfilesResponse
	nil,                                   // 32: auth.v1.CheckRequest.ContextEntry
	(*timestamppb.Timestamp)(nil),         // 33: google.protobuf.Timestamp
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	2,  // 0: auth.v1.ListKeysResponse.keys:type_name -> auth.v1.Key
	33, // 1: auth.v1.Key.not_after:type_name -> google.protobuf.Timestamp
	6,  // 2: auth.v1.RevokedSinceResponse.revocations:type_name -> auth.v1.Revocation
	33, // 3: auth.v1.Revocation.ts:type_name -> google.protobuf.Timestamp
	33, // 4: auth.v1.IntrospectResponse.expires_at:type_name -> google.protobuf.Timestamp
	10, // 5: auth.v1.ExchangeResponse.identity:type_name -> auth.v1.SessionIdentity
	33, // 6: auth.v1.ExchangeResponse.expires_at:type_name -> google.protobuf.Timestamp
	10, // 7: auth.v1.MintTokenResponse.identity:type_name -> auth.v1.SessionIdentity
	33, // 8: auth.v1.MintTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	33, // 9: auth.v1.MintEnrollmentTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	32, // 10: auth.v1.CheckRequest.context:type_name -> auth.v1.CheckRequest.ContextEntry
	21, // 11: auth.v1.BatchCheckRequest.permissions:type_name -> auth.v1.PermissionRef
	19, // 12: auth.v1.BatchCheckResponse.results:type_name -> auth.v1.CheckResponse
	25, // 13: auth.v1.RegisterPermissionsRequest.permissions:type_name -> auth.v1.PermissionDef
	24, // 14: auth.v1.RegisterPermissionsRequest.builtin_grants:type_name -> auth.v1.BuiltinGrant
	30, // 15: auth.v1.LookupProfilesResponse.profiles:type_name -> auth.v1.PublicProfile
	0,  // 16: auth.v1.Keys.List:input_type -> auth.v1.ListKeysRequest
	3,  // 17: auth.v1.Sessions.RevokedSince:input_type -> auth.v1.RevokedSinceRequest
	5,  // 18: auth.v1.Sessions.Watch:input_type -> auth.v1.WatchRequest
	7,  // 19: auth.v1.Sessions.Introspect:input_type -> auth.v1.IntrospectRequest
	9,  // 20: auth.v1.Sessions.Exchange:input_type -> auth.v1.ExchangeRequest
	12, // 21: auth.v1.Sessions.MintToken:input_type -> auth.v1.MintTokenRequest
	14, // 22: auth.v1.Enrollment.MintEnrollmentToken:input_type -> auth.v1.MintEnrollmentTokenRequest
	16, // 23: auth.v1.Enrollment.VerifyEnrollmentToken:input_type -> auth.v1.VerifyEnrollmentTokenRequest
	18, // 24: auth.v1.Authorization.Check:input_type -> auth.v1.CheckRequest
	20, // 25: auth.v1.Authorization.BatchCheck:input_type -> auth.v1.BatchCheckRequest
	23, // 26: auth.v1.Authorization.RegisterPermissions:input_type -> auth.v1.RegisterPermissionsRequest
	29, // 27: auth.v1.Profiles.Lookup:input_type -> auth.v1.LookupProfilesRequest
	27, // 28: auth.v1.Profiles.ListMembers:input_type -> auth.v1.ListMembersRequest
	1,  // 29: auth.v1.Keys.List:output_type -> auth.v1.ListKeysResponse
	4,  // 30: auth.v1.Sessions.RevokedSince:output_type -> auth.v1.RevokedSinceResponse
	6,  // 31: auth.v1.Sessions.Watch:output_type -> auth.v1.Revocation
	8,  // 32: auth.v1.Sessions.Introspect:output_type -> auth.v1.IntrospectResponse
	11, // 33: auth.v1.Sessions.Exchange:output_type -> auth.v1.ExchangeResponse
	13, // 34: auth.v1.Sessions.MintToken:output_type -> auth.v1.MintTokenResponse
	15, // 35: auth.v1.Enrollment.MintEnrollmentToken:output_type -> auth.v1.MintEnrollmentTokenResponse
	17, // 36: auth.v1.Enrollment.VerifyEnrollmentToken:output_type -> auth.v1.VerifyEnrollmentTokenResponse
	19, // 37: auth.v1.Authorization.Check:output_type -> auth.v1.CheckResponse
	22, // 38: auth.v1.Authorization.BatchCheck:output_type -> auth.v1.BatchCheckResponse
	26, // 39: auth.v1.Authorization.RegisterPermissions:output_type -> auth.v1.RegisterPermissionsResponse
	31, // 40: auth.v1.Profiles.Lookup:output_type -> auth.v1.LookupProfilesResponse
	28, // 41: auth.v1.Profiles.ListMembers:output_type -> auth.v1.ListMembersResponse
	29, // [29:42] is the sub-list for method output_type
	16, // [16:29] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
